// Copyright 2016 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.!

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: sentencepiece.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SentencePieceText manages a user-facing source sentence,
// postprocessed target sentence, and internal segmentation
// with byte offsets.
type SentencePieceText struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User input or postprocessed text. This should be immutable
	// since the byte range in SentencePiece is pointing to a span over this
	// text. Meta symbols for whitespaces are not included.
	Text *string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	// A sequence of sentence pieces. These `pieces` are guaranteed to be ordered
	// in increasing order of `begin` field. Except for the last piece, `end` of
	// each piece is always equal to `begin` of the next piece.
	Pieces []*SentencePieceText_SentencePiece `protobuf:"bytes,2,rep,name=pieces" json:"pieces,omitempty"`
	// Score (usually log probability) for MultiSentencePieceText.
	Score           *float32 `protobuf:"fixed32,3,opt,name=score" json:"score,omitempty"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SentencePieceText) Reset() {
	*x = SentencePieceText{}
	mi := &file_sentencepiece_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentencePieceText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentencePieceText) ProtoMessage() {}

func (x *SentencePieceText) ProtoReflect() protoreflect.Message {
	mi := &file_sentencepiece_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentencePieceText.ProtoReflect.Descriptor instead.
func (*SentencePieceText) Descriptor() ([]byte, []int) {
	return file_sentencepiece_proto_rawDescGZIP(), []int{0}
}

func (x *SentencePieceText) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *SentencePieceText) GetPieces() []*SentencePieceText_SentencePiece {
	if x != nil {
		return x.Pieces
	}
	return nil
}

func (x *SentencePieceText) GetScore() float32 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

type NBestSentencePieceText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nbests        []*SentencePieceText   `protobuf:"bytes,1,rep,name=nbests" json:"nbests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NBestSentencePieceText) Reset() {
	*x = NBestSentencePieceText{}
	mi := &file_sentencepiece_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NBestSentencePieceText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NBestSentencePieceText) ProtoMessage() {}

func (x *NBestSentencePieceText) ProtoReflect() protoreflect.Message {
	mi := &file_sentencepiece_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NBestSentencePieceText.ProtoReflect.Descriptor instead.
func (*NBestSentencePieceText) Descriptor() ([]byte, []int) {
	return file_sentencepiece_proto_rawDescGZIP(), []int{1}
}

func (x *NBestSentencePieceText) GetNbests() []*SentencePieceText {
	if x != nil {
		return x.Nbests
	}
	return nil
}

type SentencePieceText_SentencePiece struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Internal representation for the decoder.
	// - Decoder can use |piece| as a basic token.
	// - the piece must be non-empty.
	// - A whitespace is replaced with a meta symbol.
	// - Concatenation of pieces is not always the same as the |text|.
	Piece *string `protobuf:"bytes,1,opt,name=piece" json:"piece,omitempty"`
	// Vocabulary id.
	Id *uint32 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	// External representation for the client.
	//   - It is always guaranteed that
	//     text.substr(begin, end - begin) == surface.
	//   - Concatenation of surface is always the same as the |text|.
	//   - |surface| may contain whitespaces.
	//   - |surface| may be empty if the piece encodes
	//     a control vocabulary. e.g., <s>, </s>, <unk>.
	//   - When |surface| is empty, always begin == end. (zero-length span).
	Surface         *string `protobuf:"bytes,3,opt,name=surface" json:"surface,omitempty"`
	Begin           *uint32 `protobuf:"varint,4,opt,name=begin" json:"begin,omitempty"`
	End             *uint32 `protobuf:"varint,5,opt,name=end" json:"end,omitempty"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SentencePieceText_SentencePiece) Reset() {
	*x = SentencePieceText_SentencePiece{}
	mi := &file_sentencepiece_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentencePieceText_SentencePiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentencePieceText_SentencePiece) ProtoMessage() {}

func (x *SentencePieceText_SentencePiece) ProtoReflect() protoreflect.Message {
	mi := &file_sentencepiece_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentencePieceText_SentencePiece.ProtoReflect.Descriptor instead.
func (*SentencePieceText_SentencePiece) Descriptor() ([]byte, []int) {
	return file_sentencepiece_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SentencePieceText_SentencePiece) GetPiece() string {
	if x != nil && x.Piece != nil {
		return *x.Piece
	}
	return ""
}

func (x *SentencePieceText_SentencePiece) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SentencePieceText_SentencePiece) GetSurface() string {
	if x != nil && x.Surface != nil {
		return *x.Surface
	}
	return ""
}

func (x *SentencePieceText_SentencePiece) GetBegin() uint32 {
	if x != nil && x.Begin != nil {
		return *x.Begin
	}
	return 0
}

func (x *SentencePieceText_SentencePiece) GetEnd() uint32 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

var File_sentencepiece_proto protoreflect.FileDescriptor

const file_sentencepiece_proto_rawDesc = "" +
	"\n" +
	"\x13sentencepiece.proto\x12\rsentencepiece\"\x95\x02\n" +
	"\x11SentencePieceText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12F\n" +
	"\x06pieces\x18\x02 \x03(\v2..sentencepiece.SentencePieceText.SentencePieceR\x06pieces\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x1a\x82\x01\n" +
	"\rSentencePiece\x12\x14\n" +
	"\x05piece\x18\x01 \x01(\tR\x05piece\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x18\n" +
	"\asurface\x18\x03 \x01(\tR\asurface\x12\x14\n" +
	"\x05begin\x18\x04 \x01(\rR\x05begin\x12\x10\n" +
	"\x03end\x18\x05 \x01(\rR\x03end*\t\b\xc8\x01\x10\x80\x80\x80\x80\x02*\t\b\xc8\x01\x10\x80\x80\x80\x80\x02\"R\n" +
	"\x16NBestSentencePieceText\x128\n" +
	"\x06nbests\x18\x01 \x03(\v2 .sentencepiece.SentencePieceTextR\x06nbestsB\x02H\x03"

var (
	file_sentencepiece_proto_rawDescOnce sync.Once
	file_sentencepiece_proto_rawDescData []byte
)

func file_sentencepiece_proto_rawDescGZIP() []byte {
	file_sentencepiece_proto_rawDescOnce.Do(func() {
		file_sentencepiece_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentencepiece_proto_rawDesc), len(file_sentencepiece_proto_rawDesc)))
	})
	return file_sentencepiece_proto_rawDescData
}

var file_sentencepiece_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sentencepiece_proto_goTypes = []any{
	(*SentencePieceText)(nil),               // 0: sentencepiece.SentencePieceText
	(*NBestSentencePieceText)(nil),          // 1: sentencepiece.NBestSentencePieceText
	(*SentencePieceText_SentencePiece)(nil), // 2: sentencepiece.SentencePieceText.SentencePiece
}
var file_sentencepiece_proto_depIdxs = []int32{
	2, // 0: sentencepiece.SentencePieceText.pieces:type_name -> sentencepiece.SentencePieceText.SentencePiece
	0, // 1: sentencepiece.NBestSentencePieceText.nbests:type_name -> sentencepiece.SentencePieceText
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sentencepiece_proto_init() }
func file_sentencepiece_proto_init() {
	if File_sentencepiece_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentencepiece_proto_rawDesc), len(file_sentencepiece_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sentencepiece_proto_goTypes,
		DependencyIndexes: file_sentencepiece_proto_depIdxs,
		MessageInfos:      file_sentencepiece_proto_msgTypes,
	}.Build()
	File_sentencepiece_proto = out.File
	file_sentencepiece_proto_goTypes = nil
	file_sentencepiece_proto_depIdxs = nil
}
