// Code generated by cmd/gen_normdata. DO NOT EDIT.

package normalizer

// unicodeScriptMap maps Unicode codepoints to their script names.
var unicodeScriptMap = map[rune]string{}

// GetUnicodeScript returns the Unicode script name for a given rune.
func GetUnicodeScript(r rune) string {
	if script, ok := unicodeScriptMap[r]; ok {
		return script
	}
	return "Unknown"
}
