#!/bin/bash
#
# Gitea Setup Script for aModels
# Automates initial configuration of Gitea service
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AMODELS_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running in correct directory
if [ ! -f "$SCRIPT_DIR/docker-compose.yml" ]; then
    log_error "docker-compose.yml not found. Run this script from infrastructure/docker/brev/"
    exit 1
fi

log_info "Starting Gitea setup for aModels..."

# Step 1: Start PostgreSQL
log_info "Step 1/7: Starting PostgreSQL..."
docker-compose up -d postgres
log_info "Waiting for PostgreSQL to be ready..."
sleep 10

# Verify PostgreSQL is running
if ! docker exec postgres pg_isready -U postgres > /dev/null 2>&1; then
    log_error "PostgreSQL is not ready. Please check: docker-compose logs postgres"
    exit 1
fi
log_success "PostgreSQL is ready"

# Step 2: Verify Gitea database exists
log_info "Step 2/7: Verifying Gitea database..."
if docker exec postgres psql -U postgres -lqt | cut -d \| -f 1 | grep -qw gitea; then
    log_success "Gitea database exists"
else
    log_warning "Gitea database not found, will be created on first startup"
fi

# Step 3: Start Gitea
log_info "Step 3/7: Starting Gitea service..."
docker-compose up -d gitea
log_info "Waiting for Gitea to be ready (this may take up to 60 seconds)..."

# Wait for Gitea to be healthy
MAX_RETRIES=30
RETRY_COUNT=0
while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    if curl -sf http://localhost:3000/api/healthz > /dev/null 2>&1; then
        log_success "Gitea is ready!"
        break
    fi
    echo -n "."
    sleep 2
    RETRY_COUNT=$((RETRY_COUNT + 1))
done
echo ""

if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
    log_error "Gitea failed to start within timeout. Check logs: docker-compose logs gitea"
    exit 1
fi

# Step 4: Create admin user
log_info "Step 4/7: Creating admin user..."
read -p "Create admin user? (y/n, default: y): " CREATE_ADMIN
CREATE_ADMIN=${CREATE_ADMIN:-y}

if [ "$CREATE_ADMIN" = "y" ]; then
    read -p "Admin username (default: admin): " ADMIN_USER
    ADMIN_USER=${ADMIN_USER:-admin}
    
    read -sp "Admin password (default: admin123): " ADMIN_PASS
    echo ""
    ADMIN_PASS=${ADMIN_PASS:-admin123}
    
    read -p "Admin email (default: admin@localhost): " ADMIN_EMAIL
    ADMIN_EMAIL=${ADMIN_EMAIL:-admin@localhost}
    
    if docker exec gitea gitea admin user create \
        --username "$ADMIN_USER" \
        --password "$ADMIN_PASS" \
        --email "$ADMIN_EMAIL" \
        --admin 2>/dev/null; then
        log_success "Admin user '$ADMIN_USER' created"
    else
        log_warning "Admin user may already exist or creation failed"
    fi
fi

# Step 5: Create extract-service organization
log_info "Step 5/7: Creating 'extract-service' organization..."
read -p "Create extract-service organization? (y/n, default: y): " CREATE_ORG
CREATE_ORG=${CREATE_ORG:-y}

if [ "$CREATE_ORG" = "y" ]; then
    log_info "Please create API token first in Gitea UI"
    log_info "Open: http://localhost:3000"
    log_info "Login → Settings → Applications → Generate New Token"
    echo ""
    read -p "Enter API token (or press Enter to skip): " API_TOKEN
    
    if [ -n "$API_TOKEN" ]; then
        ORG_RESPONSE=$(curl -s -X POST http://localhost:3000/api/v1/orgs \
            -H "Authorization: token $API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
                "username": "extract-service",
                "full_name": "Extract Service",
                "description": "Organization for extracted code repositories",
                "visibility": "public"
            }' 2>&1)
        
        if echo "$ORG_RESPONSE" | grep -q '"username":"extract-service"'; then
            log_success "Organization 'extract-service' created"
        else
            log_warning "Organization creation failed or already exists"
        fi
    else
        log_warning "Skipped organization creation (no token provided)"
        log_info "You can create it manually in Gitea UI"
    fi
fi

# Step 6: Generate webhook secret
log_info "Step 6/7: Generating webhook secret..."
WEBHOOK_SECRET=$(openssl rand -hex 32)
log_success "Webhook secret generated"

# Step 7: Create .env file
log_info "Step 7/7: Creating environment configuration..."
ENV_FILE="$AMODELS_ROOT/.env.gitea"

cat > "$ENV_FILE" <<EOF
# Gitea Configuration for aModels
# Generated by setup-gitea.sh on $(date)

# Gitea Service URL
# - For Docker services: use http://gitea:3000
# - For host services: use http://localhost:3000
export GITEA_URL="http://localhost:3000"
export GITEA_URL_DOCKER="http://gitea:3000"

# Gitea API Token
# Generate in Gitea UI: Settings → Applications → Generate New Token
export GITEA_TOKEN="${API_TOKEN:-YOUR_TOKEN_HERE}"

# Webhook Secret for secure webhook delivery
export GITEA_WEBHOOK_SECRET="$WEBHOOK_SECRET"

# Organization for extracted code repositories
export GITEA_OWNER="extract-service"

# Default repository settings
export GITEA_REPO_PREFIX="extracted-code"
export GITEA_AUTO_CREATE="true"
EOF

log_success "Environment file created: $ENV_FILE"

# Summary
echo ""
echo "=========================================="
echo "   Gitea Setup Complete!"
echo "=========================================="
echo ""
echo "Gitea URL:      http://localhost:3000"
echo "Admin User:     ${ADMIN_USER:-admin}"
echo "Admin Password: ${ADMIN_PASS:-admin123}"
echo ""
echo "Next Steps:"
echo "1. Load environment variables:"
echo "   source $ENV_FILE"
echo ""
echo "2. Generate API token in Gitea:"
echo "   - Open http://localhost:3000"
echo "   - Login → Settings → Applications"
echo "   - Generate New Token (select 'repo' scope)"
echo "   - Update GITEA_TOKEN in $ENV_FILE"
echo ""
echo "3. Configure Extract service:"
echo "   - Export environment variables"
echo "   - Restart Extract service"
echo ""
echo "4. Test connection:"
echo "   curl http://localhost:8083/gitea/repositories \\"
echo "     -H \"X-Gitea-URL: http://localhost:3000\" \\"
echo "     -H \"X-Gitea-Token: YOUR_TOKEN\""
echo ""
echo "Documentation: $SCRIPT_DIR/GITEA_SETUP.md"
echo "=========================================="
